# Documentation: http://docs.travis-ci.com/user/languages/julia/
sudo: false
language: julia
os:
  - linux
  #- osx
julia:
  #- release
  - nightly

# dependent apt packages
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - wget
      - git
      - libcurl4-openssl-dev
      - unzip
      - libatlas-dev
      - libopencv-dev
      - gcc-4.8
      - g++-4.8
      - clang

before_install:
  - export TRAVIS=test/travis
  - source $TRAVIS/setup_env.sh
  - source $TRAVIS/build_mxnet.sh

notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("MXNet"); Pkg.test("MXNet"; coverage=true)'
